---
on: [push, pull_request]
name: lint-test

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       nvim-versions: ["nightly"]
  #   name: test
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #
  #     - uses: rhysd/action-setup-vim@v1
  #       with:
  #         neovim: true
  #         version: ${{ matrix.nvim-versions }}
  #
  #     - name: run tests
  #       run: make test
